### ISSUE TITLE
Manual Baselines

### ISSUE THREAD

**Issue by jneuner-mitre** [mitre/heimdall#131]
As an Information System Owner, I need to be able to define and track manual tests so I know when control compliance needs to be reevaluated.

**Comment by jneuner-mitre** [comment]
Ideally, I have a profile that describes the test that needs to take place, including  the frequency to repeat the test.  When I complete the manual check, I add data about the outcome of the check and the date that the check was performed. and date of the last manual check.  

Data model looks something like this:
```yaml
- name: manual_controls
    description: '<words here>'
    type: array
    value:
      - Control_ID: V-71626
        Parent ID: [nist:CM-99,fiscam:ABC-123]
        Status: [Pass/Fail/Incomplete]
        Updated: YYYY-MM-DD
        Frequency: [Annually, Semi-Annually, Quarterly, Monthly, Bi-weekly, Weekly, Every_3_Days, Daily] based on absolute calendar of January 1st as the start
        Frequency_start_date: YYYY-MM-DD [optional, sets the start of the “year” for frequency]
        Explanation: {statement from the ISSO confirming that they've done whatever the check/fix text said and why/whynot its all good/bad}
```
